version : '3'

services:

    postgresql-dev:
        image: postgres:13.5
        ports:
            - '5432:5432'
        environment:
            POSTGRESQL_USERNAME: postgres
            POSTGRESQL_PASSWORD: postgres
            POSTGRES_PASSWORD: postgres
            POSTGRESQL_DATABASE: postgres

    app:
        image: quarkus/image-detection-jvm
        environment:
            QUARKUS_DATASOURCE_JDBC_URL: jdbc:postgresql://postgresql-dev:5432/postgres
            QUARKUS_HTTP_PORT: 8080
            QUARKUS_LAUNCH_DEV_MODE: "true"
        restart: always
        depends_on:
            - postgresql-dev
        ports:
            - "8080:8080"
            - "5005:5005"
